# Generated by Django 5.1.3 on 2024-11-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
