# Generated by Django 5.1.3 on 2024-12-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='passW',
        ),
    ]
