# Generated by Django 5.1.3 on 2025-01-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0005_remove_customuser_name_remove_customuser_passw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
