# Generated by Django 5.1.3 on 2025-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='bio',
            field=models.CharField(default='Garden Bio', max_length=255),
            preserve_default=False,
        ),
    ]
