# Generated by Django 5.1.3 on 2025-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0008_garden_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='ownerEmail',
            field=models.EmailField(default='will@work.com', max_length=254),
            preserve_default=False,
        ),
    ]
