# Generated by Django 5.1.3 on 2025-02-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0009_garden_owneremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='ownerEmail',
        ),
        migrations.AddField(
            model_name='garden',
            name='ownerUsername',
            field=models.CharField(default='dog', max_length=255),
            preserve_default=False,
        ),
    ]
