# Generated by Django 5.1.3 on 2025-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0011_garden_ownerid_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='gardenName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
