# Generated by Django 5.1.3 on 2025-02-23 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0012_message_gardenname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='userID',
            new_name='senderID',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='ownerUsername',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='gardenName',
        ),
        migrations.AddField(
            model_name='garden',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
